name: Setup Neon
author: nhedger
description: Setup Neon CLI in GitHub Actions
branding:
  color: white
  icon: terminal
inputs:
  token:
    description: GitHub Actions token to authenticate API requests
    required: true
    default: ${{ github.token }}
  version:
    description: The version of the Neon CLI to install
    required: true
    default: latest
runs:
  using: 'node20'
  main: 'dist/index.js'
