name: Integrate

on:
  push:
    branches: [ main, "releases/v*" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build action
        run: bun run build

  coding-standards:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Biome
      uses: biomejs/setup-biome@v2

    - name: Check coding standards
      run: biome ci --reporter github .
